### ISSUE TITLE
Problems obtaining data

### ISSUE THREAD

**Issue by pssguy** [EvanOdell/mnis#3]
Thanks for this package
However, I am having trouble getting started

e.g

```
> mnis_basic_details()
Error: ID cannot be empty
> ref_elections()
Warning message:
JSON string contains (illegal) UTF8 byte-order-mark! 
```

**Comment by EvanOdell** [comment]
Thanks for these. I've added code to remove BOMs from the API responses, and changed the default error behaviour for `mnis_additional` functions, which includes `mnis_basic_details`. This is all in the latest v0.2.2 release on GitHub.
