### ISSUE TITLE
Error in `mnis_full_biog` column names

### ISSUE THREAD

**Issue by evanodell** [EvanOdell/mnis#4]
`mnis_full_biog` doesn't return column names, just V1, V2, etc. Long term solution is to more closely preserve structure of data from API, storing dataframes of government posts, etc, in listcols rather than as separate columns.

**Comment by nicucalcea** [comment]
Having the same issue with `mnis_committees`. Anything I can do to get around it?

**Comment by evanodell** [comment]
The latest development version on github is a quick fix, returns a list instead. It's a bit of a pain to work with if you're not used to using lists in R, and I'm trying to find a way to make it more user friendly but it should work for you. Apologies for the delay.
